spring.application.name=Typingapp

server.port=8081

# PostgreSQL (Neon)

spring.datasource.url=jdbc:postgresql://ep-wandering-firefly-auymdf92-pooler.c-10.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_OS4Vxi9BptqF

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

google.client.id=286336470111-jv5lj14s43ftpafrofq1fudu3d3lsnk5.apps.googleusercontent.com

# Email

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ghasavindya@gmail.com
spring.mail.password=iuukkuhluooshpdt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.security=TRACE